### ISSUE TITLE
Antidot\Application\Http\Application interface should be mixed $middleware

### ISSUE THREAD

**Issue by peter279k** [antidot-framework/antidot-framework#30]
**Describe the bug**
The `$middleware` parameter should be multiple types.

**To Reproduce**
1. Running `composer create-project antidot-fw/antidot-framework-starter project-name` command.
2. Opening the `./router/routes.php` file.
3. Looking at following comments on `./router/routes.php` file:

```
/**
 * Setup routes with a single request method:
 *
 * $app->get('/', App\Handler\HomePageHandler::class, 'home');
 * $app->post('/album', App\Handler\AlbumCreateHandler::class, 'album.create');
 * $app->put('/album/:id', App\Handler\AlbumUpdateHandler::class, 'album.put');
 * $app->patch('/album/:id', App\Handler\AlbumUpdateHandler::class, 'album.patch');
 * $app->delete('/album/:id', App\Handler\AlbumDeleteHandler::class, 'album.delete');
 *
 * Or with multiple request methods:
 *
 * $app->route('/contact', App\Handler\ContactHandler::class, ['GET', 'POST', ...], 'contact');
 */
```
```
**Expected behavior**
The `$app->get` method can allow array or string type for second parameter (`$middleware`).

But above method only allows the `array` type for `$middleware` parameter.

** Result behavior**
App\Application\Http\Handler\ApiPage

<?php
class ApiPage implements RequestHandlerInterface { }
<?php
class ApiPage implements RequestHandlerInterface
Expected type 'array'. Found 'string'.

```

And the error log is as follows:

```TEXT
[Tue Jan 19 19:27:41 2021] 127.0.0.1:54546 [500]: GET /api - Uncaught TypeError: Argument 2 passed to Antidot\Application\Http\WebServerApplication::get() must be of the type array, string given, called in /data/cloud-printer-api/router/routes.php on line 26 and defined in /data/cloud-printer-api/vendor/antidot-fw/framework/src/Application/Http/WebServerApplication.php:43
Stack trace:
#0 /data/cloud-printer-api/router/routes.php(26): Antidot\Application\Http\WebServerApplication->get()
#1 /data/cloud-printer-api/public/index.php(26): {closure}()
#2 /data/cloud-printer-api/public/index.php(28): {closure}()
#3 {main}
  thrown in /data/cloud-printer-api/vendor/antidot-fw/framework/src/Application/Http/WebServerApplication.php on line 43
```

**Additional context**
N/A

**Comment by peter279k** [comment]
It's worked if using following codes:

```
$app->get('/api', [ApiPage::class], 'api');
```

**Comment by kpicaza** [comment]
Thanks for reporting and for the patch in the documentation at the starter package(I will apply to reactive starter too);- D. Initially, it allows using both string and array, but to avoid the type check before loading a route, I decide to only allow arrays, we can discuss it because is more user friendly to allow both types,

**Comment by peter279k** [comment]
@kpicaza, thanks for your reply.

There're two points about this issue:

- Using the `array` type for this parameter.
- Using the `array` or `string` types for this parameter.

I prefer using the `array` type is good because it can do native type checking for developers, but it's not useless for developers to know the parameter description.

I think using the `string` or `array` type can be good for developers, but it cannot do native type checking for this approach.

**Comment by kpicaza** [comment]
> I prefer using the array type is good because it can do native type checking for developers, but it's not useless for developers to know the parameter description.

@peter279k Me too, we can leave it as is, I think that with the correct documentation specification in the `routes.php` file(your patch), and the type error that PHP throws if the user uses a string instead of an array should be enough.

**Comment by kpicaza** [comment]
@peter279k This line is wrong too:

```
 * $app->route('/contact', App\Handler\ContactHandler::class, ['GET', 'POST', ...], 'contact');
```

`Application::route` method does not allow the passing of an array of HTTP methods to it, It only accepts one.

I don't know if is better to not allow at all(deprecate route method on public API), or modify the interface to accept arrays instead of strings:

Having an array instead of strings will allow passing different HTTP methods to the same "action"|"controller" in one line, but I don't like too much this practice, I prefer an action per method approach, what do you think?

Also if the user wants to use the same action for different methods you can do adding two lines to the router file

**Comment by peter279k** [comment]
The `Application::route` method comments are as follows:

```PHP
......
    /**
     * @param array<MiddlewareInterface> $middleware
     */
    public function route(string $method, string $uri, array $middleware, string $name): void;
......
```

It seems that the `$uri` parameter should change into `public function route(string $uri, array $middleware, array $method, string $name): void;`.

What do you think about that?

**Comment by kpicaza** [comment]
:+1:  LGTM, but we have to be aware of the BC break with https://github.com/antidot-framework/react-framework/blob/644b57144803c07b627fb4683a939bd8e112034c/src/ReactApplication.php#L79 :rocket::rocket::rocket:

**Comment by peter279k** [comment]
>  LGTM, but we have to be aware of the BC break with https://github.com/antidot-framework/react-framework/blob/644b57144803c07b627fb4683a939bd8e112034c/src/ReactApplication.php#L79

Yes. It's breaking change. To avoid breaking change, I think it should keep the parameter orders :).

**Comment by kpicaza** [comment]
Hi @peter279k, We can make the change, the current version is a 0.x.x, we can do a bc break an then go up a minor release 0.2.0, maybe it's not the correctest way, but if we left this method here, the problem will increase around the time because the users will continue having a choice to use it.

**Comment by peter279k** [comment]
If we want to do BC breaking change, I think the following PHP codes should be modified:

- https://github.com/antidot-framework/antidot-framework/blob/master/src/Application/Http/Application.php
- https://github.com/antidot-framework/react-framework/blob/644b57144803c07b627fb4683a939bd8e112034c/src/ReactApplication.php#L79

Are there any related PHP files should be modified?

**Comment by kpicaza** [comment]
> If we want to do BC breaking change, I think the following PHP codes should be modified:
>
> https://github.com/antidot-framework/antidot-framework/blob/master/src/Application/Http/Application.php#L48
> https://github.com/antidot-framework/react-framework/blob/644b57144803c07b627fb4683a939bd8e112034c/src/ReactApplication.php#L79

You are right, these are the affected files  :+1: 

> Are there any related PHP files should be modified?

No, we don't use the method out of the Application itself.

Thanks a lot, @peter279k ;-D

**Comment by peter279k** [comment]
The https://github.com/antidot-framework/antidot-framework/blob/master/src/Application/Http/WebServerApplication.php#L73 should be modified, too.
